name: PebbleAntiVPN
version: '${project.version}'
main: pebbleantivpn.pebbleantivpn.PebbleAntiVPNSpigot
authors: [ Binkie ]
description: High quality free AntiVPN.
commands:
  pav:
    description: Main Command For PebbleAntiVPN
